name: Build and Release Stallplatz-Management1

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  APP_NAME: StallplatzManager

jobs:
  build-and-release:
    strategy:
      matrix:
        include:
          - os_name: Windows
            os_runner: windows-latest
            target_id: windows
          - os_name: macOS (Apple Silicon)
            os_runner: macos-latest
            target_id: macos-arm64
          - os_name: macOS (Intel)
            os_runner: macos-13
            target_id: macos-intel
          - os_name: Linux
            os_runner: ubuntu-latest
            target_id: linux

    runs-on: ${{ matrix.os_runner }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install PyInstaller and Application Dependencies (pinned)
      run: |
        python -m pip install --upgrade pip wheel
        # Pin PyInstaller + hooks-contrib to avoid numpy hiddenimport bug
        pip install --no-cache-dir "pyinstaller==6.7.0" "pyinstaller-hooks-contrib==2024.10"
        # App dependencies
        pip install --no-cache-dir -r requirements.txt
        # Pin numpy/pandas to stable builds for Py 3.12
        pip install --no-cache-dir "numpy==2.0.1" "pandas==2.2.2" Pillow
        python -c "import sys,platform; print('Python:', sys.version); print('Platform:', platform.platform())"
        pip freeze
      timeout-minutes: 10

    # Windows: ICO erzeugen
    - name: Generate Windows Icon (ICO)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        $ICON_SOURCE_PNG="assets/logo.png"
        if (-Not (Test-Path $ICON_SOURCE_PNG)) {
          Write-Host "assets/logo.png nicht gefunden. Überspringe ICO-Erstellung."
          exit 0
        }
        choco install imagemagick --force --no-progress
        magick "$ICON_SOURCE_PNG" -resize 256x256 scaled_icon_source.png
        magick convert scaled_icon_source.png -define icon:autoresize=256,128,64,48,32,16 icon.ico
        Remove-Item scaled_icon_source.png -ErrorAction SilentlyContinue

    # macOS: ICNS erzeugen
    - name: Generate macOS Icon (ICNS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        ICON_SOURCE_PNG="assets/logo.png"
        if [ ! -f "$ICON_SOURCE_PNG" ]; then
          echo "assets/logo.png nicht gefunden. Überspringe ICNS-Erstellung."
          exit 0
        fi
        mkdir -p icon.iconset
        sips -z 512 512 "$ICON_SOURCE_PNG" --out scaled_icon_source.png
        sips -z 16 16 scaled_icon_source.png --out icon.iconset/icon_16x16.png
        sips -z 32 32 scaled_icon_source.png --out icon.iconset/icon_16x16@2x.png
        sips -z 32 32 scaled_icon_source.png --out icon.iconset/icon_32x32.png
        sips -z 64 64 scaled_icon_source.png --out icon.iconset/icon_32x32@2x.png
        sips -z 128 128 scaled_icon_source.png --out icon.iconset/icon_128x128.png
        sips -z 256 256 scaled_icon_source.png --out icon.iconset/icon_128x128@2x.png
        sips -z 256 256 scaled_icon_source.png --out icon.iconset/icon_256x256.png
        sips -z 512 512 scaled_icon_source.png --out icon.iconset/icon_256x256@2x.png
        sips -z 1024 1024 scaled_icon_source.png --out icon.iconset/icon_512x512@2x.png
        iconutil -c icns icon.iconset -o icon.icns
        rm -r icon.iconset
        rm -f scaled_icon_source.png

    # Linux: PNG-Icon erzeugen
    - name: Generate Linux Icon (PNG)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        ICON_SOURCE_PNG="assets/logo.png"
        if [ ! -f "$ICON_SOURCE_PNG" ]; then
          echo "assets/logo.png nicht gefunden. Überspringe PNG-Icon-Erstellung."
          exit 0
        fi
        sudo apt-get update
        sudo apt-get install -y imagemagick
        convert "$ICON_SOURCE_PNG" -resize 256x256 icon.png

    - name: Extract version from tag
      id: get_version
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Build Application with PyInstaller
      timeout-minutes: 25
      shell: bash
      run: |
        APP_VERSION=${{ steps.get_version.outputs.VERSION || 'dev' }}
        echo "Building version $APP_VERSION for ${{ matrix.os_name }} (${RUNNER_OS})"

        DATA_SEPARATOR=$([ "$RUNNER_OS" == "Windows" ] && echo ";" || echo ":")
        args=(
          --noconfirm
          main.py
          --name "${APP_NAME}"
          --clean
          --windowed
          --collect-all qtawesome
          --collect-all numpy
          --collect-all pandas
          --hidden-import "PySide6.QtSvg"
          --hidden-import "PySide6.QtNetwork"
          --hidden-import "PySide6.QtPrintSupport"
        )

        if [ -d "assets" ]; then
          args+=(--add-data "assets${DATA_SEPARATOR}assets")
        fi

        if [ "$RUNNER_OS" == "Windows" ] && [ -f "icon.ico" ]; then
          args+=(--icon "icon.ico")
        elif [ "$RUNNER_OS" == "macOS" ] && [ -f "icon.icns" ]; then
          args+=(--icon "icon.icns")
        elif [ "$RUNNER_OS" == "Linux" ]; then
          if [ -f "icon.png" ]; then
            args+=(--icon "icon.png")
          elif [ -f "assets/logo.png" ]; then
            args+=(--icon "assets/logo.png")
          fi
        fi

        pyinstaller "${args[@]}"

        echo "Dist directory content:"
        ls -R dist || true

    - name: Prepare Release Artifact
      id: prepare_artifact
      shell: bash
      run: |
        APP_VERSION="${{ steps.get_version.outputs.VERSION || 'dev' }}"
        ARTIFACT_NAME="${{ env.APP_NAME }}-v${APP_VERSION}-${{ matrix.target_id }}.zip"
        echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT

        if [ "${{ runner.os }}" == "Windows" ]; then
          powershell -Command "Compress-Archive -Path 'dist/${{ env.APP_NAME }}' -DestinationPath '${ARTIFACT_NAME}' -Force"
        elif [ "${{ runner.os }}" == "macOS" ]; then
          ditto -c -k --sequesterRsrc --keepParent "dist/${{ env.APP_NAME }}.app" "${ARTIFACT_NAME}"
        elif [ "${{ runner.os }}" == "Linux" ]; then
          cd dist
          zip -r "../${ARTIFACT_NAME}" "${{ env.APP_NAME }}"
          cd ..
        fi
        echo "Created artifact: ${ARTIFACT_NAME}"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}-Build-${{ matrix.target_id }}
        path: ${{ steps.prepare_artifact.outputs.ARTIFACT_NAME }}
        if-no-files-found: error

    - name: Create GitHub Release (attach artifacts)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.prepare_artifact.outputs.ARTIFACT_NAME }}